require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PurchaseorderItemsController do

  # This should return the minimal set of attributes required to create a valid
  # PurchaseorderItem. As you add validations to PurchaseorderItem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PurchaseorderItemsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all purchaseorder_items as @purchaseorder_items" do
      purchaseorder_item = PurchaseorderItem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:purchaseorder_items).should eq([purchaseorder_item])
    end
  end

  describe "GET show" do
    it "assigns the requested purchaseorder_item as @purchaseorder_item" do
      purchaseorder_item = PurchaseorderItem.create! valid_attributes
      get :show, {:id => purchaseorder_item.to_param}, valid_session
      assigns(:purchaseorder_item).should eq(purchaseorder_item)
    end
  end

  describe "GET new" do
    it "assigns a new purchaseorder_item as @purchaseorder_item" do
      get :new, {}, valid_session
      assigns(:purchaseorder_item).should be_a_new(PurchaseorderItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested purchaseorder_item as @purchaseorder_item" do
      purchaseorder_item = PurchaseorderItem.create! valid_attributes
      get :edit, {:id => purchaseorder_item.to_param}, valid_session
      assigns(:purchaseorder_item).should eq(purchaseorder_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PurchaseorderItem" do
        expect {
          post :create, {:purchaseorder_item => valid_attributes}, valid_session
        }.to change(PurchaseorderItem, :count).by(1)
      end

      it "assigns a newly created purchaseorder_item as @purchaseorder_item" do
        post :create, {:purchaseorder_item => valid_attributes}, valid_session
        assigns(:purchaseorder_item).should be_a(PurchaseorderItem)
        assigns(:purchaseorder_item).should be_persisted
      end

      it "redirects to the created purchaseorder_item" do
        post :create, {:purchaseorder_item => valid_attributes}, valid_session
        response.should redirect_to(PurchaseorderItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved purchaseorder_item as @purchaseorder_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        PurchaseorderItem.any_instance.stub(:save).and_return(false)
        post :create, {:purchaseorder_item => {}}, valid_session
        assigns(:purchaseorder_item).should be_a_new(PurchaseorderItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PurchaseorderItem.any_instance.stub(:save).and_return(false)
        post :create, {:purchaseorder_item => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested purchaseorder_item" do
        purchaseorder_item = PurchaseorderItem.create! valid_attributes
        # Assuming there are no other purchaseorder_items in the database, this
        # specifies that the PurchaseorderItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PurchaseorderItem.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => purchaseorder_item.to_param, :purchaseorder_item => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested purchaseorder_item as @purchaseorder_item" do
        purchaseorder_item = PurchaseorderItem.create! valid_attributes
        put :update, {:id => purchaseorder_item.to_param, :purchaseorder_item => valid_attributes}, valid_session
        assigns(:purchaseorder_item).should eq(purchaseorder_item)
      end

      it "redirects to the purchaseorder_item" do
        purchaseorder_item = PurchaseorderItem.create! valid_attributes
        put :update, {:id => purchaseorder_item.to_param, :purchaseorder_item => valid_attributes}, valid_session
        response.should redirect_to(purchaseorder_item)
      end
    end

    describe "with invalid params" do
      it "assigns the purchaseorder_item as @purchaseorder_item" do
        purchaseorder_item = PurchaseorderItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PurchaseorderItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => purchaseorder_item.to_param, :purchaseorder_item => {}}, valid_session
        assigns(:purchaseorder_item).should eq(purchaseorder_item)
      end

      it "re-renders the 'edit' template" do
        purchaseorder_item = PurchaseorderItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PurchaseorderItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => purchaseorder_item.to_param, :purchaseorder_item => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested purchaseorder_item" do
      purchaseorder_item = PurchaseorderItem.create! valid_attributes
      expect {
        delete :destroy, {:id => purchaseorder_item.to_param}, valid_session
      }.to change(PurchaseorderItem, :count).by(-1)
    end

    it "redirects to the purchaseorder_items list" do
      purchaseorder_item = PurchaseorderItem.create! valid_attributes
      delete :destroy, {:id => purchaseorder_item.to_param}, valid_session
      response.should redirect_to(purchaseorder_items_url)
    end
  end

end
