require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PurchaseordersController do

  # This should return the minimal set of attributes required to create a valid
  # Purchaseorder. As you add validations to Purchaseorder, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PurchaseordersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all purchaseorders as @purchaseorders" do
      purchaseorder = Purchaseorder.create! valid_attributes
      get :index, {}, valid_session
      assigns(:purchaseorders).should eq([purchaseorder])
    end
  end

  describe "GET show" do
    it "assigns the requested purchaseorder as @purchaseorder" do
      purchaseorder = Purchaseorder.create! valid_attributes
      get :show, {:id => purchaseorder.to_param}, valid_session
      assigns(:purchaseorder).should eq(purchaseorder)
    end
  end

  describe "GET new" do
    it "assigns a new purchaseorder as @purchaseorder" do
      get :new, {}, valid_session
      assigns(:purchaseorder).should be_a_new(Purchaseorder)
    end
  end

  describe "GET edit" do
    it "assigns the requested purchaseorder as @purchaseorder" do
      purchaseorder = Purchaseorder.create! valid_attributes
      get :edit, {:id => purchaseorder.to_param}, valid_session
      assigns(:purchaseorder).should eq(purchaseorder)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Purchaseorder" do
        expect {
          post :create, {:purchaseorder => valid_attributes}, valid_session
        }.to change(Purchaseorder, :count).by(1)
      end

      it "assigns a newly created purchaseorder as @purchaseorder" do
        post :create, {:purchaseorder => valid_attributes}, valid_session
        assigns(:purchaseorder).should be_a(Purchaseorder)
        assigns(:purchaseorder).should be_persisted
      end

      it "redirects to the created purchaseorder" do
        post :create, {:purchaseorder => valid_attributes}, valid_session
        response.should redirect_to(Purchaseorder.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved purchaseorder as @purchaseorder" do
        # Trigger the behavior that occurs when invalid params are submitted
        Purchaseorder.any_instance.stub(:save).and_return(false)
        post :create, {:purchaseorder => {}}, valid_session
        assigns(:purchaseorder).should be_a_new(Purchaseorder)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Purchaseorder.any_instance.stub(:save).and_return(false)
        post :create, {:purchaseorder => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested purchaseorder" do
        purchaseorder = Purchaseorder.create! valid_attributes
        # Assuming there are no other purchaseorders in the database, this
        # specifies that the Purchaseorder created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Purchaseorder.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => purchaseorder.to_param, :purchaseorder => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested purchaseorder as @purchaseorder" do
        purchaseorder = Purchaseorder.create! valid_attributes
        put :update, {:id => purchaseorder.to_param, :purchaseorder => valid_attributes}, valid_session
        assigns(:purchaseorder).should eq(purchaseorder)
      end

      it "redirects to the purchaseorder" do
        purchaseorder = Purchaseorder.create! valid_attributes
        put :update, {:id => purchaseorder.to_param, :purchaseorder => valid_attributes}, valid_session
        response.should redirect_to(purchaseorder)
      end
    end

    describe "with invalid params" do
      it "assigns the purchaseorder as @purchaseorder" do
        purchaseorder = Purchaseorder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Purchaseorder.any_instance.stub(:save).and_return(false)
        put :update, {:id => purchaseorder.to_param, :purchaseorder => {}}, valid_session
        assigns(:purchaseorder).should eq(purchaseorder)
      end

      it "re-renders the 'edit' template" do
        purchaseorder = Purchaseorder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Purchaseorder.any_instance.stub(:save).and_return(false)
        put :update, {:id => purchaseorder.to_param, :purchaseorder => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested purchaseorder" do
      purchaseorder = Purchaseorder.create! valid_attributes
      expect {
        delete :destroy, {:id => purchaseorder.to_param}, valid_session
      }.to change(Purchaseorder, :count).by(-1)
    end

    it "redirects to the purchaseorders list" do
      purchaseorder = Purchaseorder.create! valid_attributes
      delete :destroy, {:id => purchaseorder.to_param}, valid_session
      response.should redirect_to(purchaseorders_url)
    end
  end

end
