require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StockcodesController do

  # This should return the minimal set of attributes required to create a valid
  # Stockcode. As you add validations to Stockcode, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StockcodesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all stockcodes as @stockcodes" do
      stockcode = Stockcode.create! valid_attributes
      get :index, {}, valid_session
      assigns(:stockcodes).should eq([stockcode])
    end
  end

  describe "GET show" do
    it "assigns the requested stockcode as @stockcode" do
      stockcode = Stockcode.create! valid_attributes
      get :show, {:id => stockcode.to_param}, valid_session
      assigns(:stockcode).should eq(stockcode)
    end
  end

  describe "GET new" do
    it "assigns a new stockcode as @stockcode" do
      get :new, {}, valid_session
      assigns(:stockcode).should be_a_new(Stockcode)
    end
  end

  describe "GET edit" do
    it "assigns the requested stockcode as @stockcode" do
      stockcode = Stockcode.create! valid_attributes
      get :edit, {:id => stockcode.to_param}, valid_session
      assigns(:stockcode).should eq(stockcode)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Stockcode" do
        expect {
          post :create, {:stockcode => valid_attributes}, valid_session
        }.to change(Stockcode, :count).by(1)
      end

      it "assigns a newly created stockcode as @stockcode" do
        post :create, {:stockcode => valid_attributes}, valid_session
        assigns(:stockcode).should be_a(Stockcode)
        assigns(:stockcode).should be_persisted
      end

      it "redirects to the created stockcode" do
        post :create, {:stockcode => valid_attributes}, valid_session
        response.should redirect_to(Stockcode.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved stockcode as @stockcode" do
        # Trigger the behavior that occurs when invalid params are submitted
        Stockcode.any_instance.stub(:save).and_return(false)
        post :create, {:stockcode => {}}, valid_session
        assigns(:stockcode).should be_a_new(Stockcode)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Stockcode.any_instance.stub(:save).and_return(false)
        post :create, {:stockcode => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested stockcode" do
        stockcode = Stockcode.create! valid_attributes
        # Assuming there are no other stockcodes in the database, this
        # specifies that the Stockcode created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Stockcode.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => stockcode.to_param, :stockcode => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested stockcode as @stockcode" do
        stockcode = Stockcode.create! valid_attributes
        put :update, {:id => stockcode.to_param, :stockcode => valid_attributes}, valid_session
        assigns(:stockcode).should eq(stockcode)
      end

      it "redirects to the stockcode" do
        stockcode = Stockcode.create! valid_attributes
        put :update, {:id => stockcode.to_param, :stockcode => valid_attributes}, valid_session
        response.should redirect_to(stockcode)
      end
    end

    describe "with invalid params" do
      it "assigns the stockcode as @stockcode" do
        stockcode = Stockcode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Stockcode.any_instance.stub(:save).and_return(false)
        put :update, {:id => stockcode.to_param, :stockcode => {}}, valid_session
        assigns(:stockcode).should eq(stockcode)
      end

      it "re-renders the 'edit' template" do
        stockcode = Stockcode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Stockcode.any_instance.stub(:save).and_return(false)
        put :update, {:id => stockcode.to_param, :stockcode => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested stockcode" do
      stockcode = Stockcode.create! valid_attributes
      expect {
        delete :destroy, {:id => stockcode.to_param}, valid_session
      }.to change(Stockcode, :count).by(-1)
    end

    it "redirects to the stockcodes list" do
      stockcode = Stockcode.create! valid_attributes
      delete :destroy, {:id => stockcode.to_param}, valid_session
      response.should redirect_to(stockcodes_url)
    end
  end

end
